spring:
  application:
    name: server-gateway-zuul
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
management:
  endpoints:
    web:
      exposure:
        include: '*'