server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  application:
    name: ws-demo-userapi
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}